export interface User{
    _id: string,
    account: string,
    displayname: string,
    password: string,
    birthday: string,
    phonenumber: string,
    email: string,
    country: string,
    photo: string,
    Gender: string,
    createDate: string,
    musicType: string,
    updateDate: string,
    Role: string,
    library: [],
    likeSong: [],
    follow: [],
}